src/Entity/SkillInterface.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Stringable;

interface SkillInterface extends Stringable
{
    public function getName(): ?string;

    public function getDescription(): ?string;
}

templates/components/employment.html.twig
{% block employment_organization %}
    {% set imageWidth = 64 %}
    <div class="overflow-hidden" id="employment-{{ this.employment.id }}">
        <div class="flex flex-col md:flex-row py-5 gap-10 md:gap-6">
                <div class="flex-shrink-0 self-center md:self-start">
                    {% block employment_employer_logo %}
                        {% if this.employment.employer.logo %}
                            {{ this.employment.employer.logo|image(
                                width = imageWidth,
                                height = 'auto',
                                alt = this.employment.employer.name
                            ) }}
                        {% else %}
                            {{ svg(
                                file = 'icons/outline/building-office.svg',
                                class = 'text-emerald-600',
                                width = imageWidth,
                                height = imageWidth
                            ) }}
                        {% endif %}
                    {% endblock %}
                </div>

                <div class="basis-2/3 px-6 md:px-0 -mt-8 md:-mt-0">
                    <div class="md:flex text-center md:text-left">
                        {% block employment_title %}
                            <h3 class="text-lg font-medium leading-6 text-gray-700">{{ this.employment.title }}</h3>
                        {% endblock %}

                        {% block employment_period %}
                            <div class="text-gray-400 leading-6 md:px-2">
                                {% block employment_period_start %}
                                    <span>
                                        {{ this.employment.startAt|date('M Y') }}
                                    </span>
                                {% endblock %}

                                &hyphen;

                                {% block employment_period_end %}
                                    <span>
                                        {{ this.employment.endAt
                                        ? this.employment.endAt|date('M Y')
                                        : 'employment.present'|trans
                                        }}
                                    </span>
                                {% endblock %}

                                &hyphen;

                                {% block employment_period_duration %}
                                    <span>{{ this.employment|duration|trans }}</span>
                                {% endblock %}
                            </div>
                        {% endblock %}
                    </div>

                    {% block employment_employer %}
                        <div class="md:flex mt-4 md:mt-0 text-center md:text-left">
                            {% block employment_employer_name %}
                                <div class="leading-6 text-gray-600">
                                    {{ this.employment.employer.name }}
                                </div>
                            {% endblock %}

                            {% block employment_employer_description %}
                                <div class="text-gray-400 leading-6 md:px-2">
                                    {{ this.employment.employer.description }}
                                </div>
                            {% endblock %}
                        </div>
                    {% endblock %}

                    {% block employment_description %}
                        <div class="text-gray-600 text-lg leading-6 space-y-3 pt-4 mt-4 md:mt-0">
                            {{ this.employment.description|markdown|replace(
                                {
                                    '<ul>': '<ul class="list-disc list-inside">',
                                    '<ol>': '<ol class="list-decimal list-inside">'
                                }
                            )|raw }}
                        </div>
                    {% endblock %}
                </div>

                <div class="basis-1/3 text-sm font-medium text-gray-800 text-center self-center md:pl-4">
                    {% block employment_skills %}
                        {# Todo: Fix sorting in repository #}
                        {% for skill in this.employment.employmentSkills|sort((a, b) =>
                            b.skill.employmentSkills|length <=> a.skill.employmentSkills|length
                        ) %}
                            {{ component('skill', {skill: skill}) }}
                        {% endfor %}
                    {% endblock %}
                </div>
            </div>
    </div>
{% endblock %}

templates/components/event.html.twig
{% block event %}
    <div class="relative pb-8" id="event-{{ this.event.id }}">
        {% block event_separator %}
            {% if this.withSeparator %}
                <span class="absolute top-4 left-4 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true"></span>
            {% endif %}
        {% endblock %}

        <div class="relative flex space-x-3">
            <div>
                {% block event_icon %}
                    <span class="h-8 w-8 rounded-full bg-emerald-600 flex items-center justify-center ring-8 ring-white">
                        {{ svg(
                            file = 'icons/mini/chat-bubble-left.svg',
                            class = 'text-white',
                            width = 20,
                            height = 20,
                            fill = 'currentColor'
                        ) }}
                    </span>
                {% endblock %}
            </div>
            <div class="flex min-w-0 flex-1 justify-between space-x-4 pt-1.5">
                <div class="space-y-3">
                    {% block event_name %}
                        {% if this.event.url %}
                            <a href="{{ this.event.url }}" target="_blank" title="{{ this.event.name }}">
                        {% endif %}

                            <h3 class="font-medium text-gray-900">
                                {{ this.event.name }}
                            </h3>

                        {% if this.event.url %}
                            </a>
                        {% endif %}
                    {% endblock %}

                    {% block event_description %}
                        <div class="text-sm text-gray-500 leading-5 space-y-4">
                            {{ this.event.description|markdown|replace(
                                {
                                    '<ul>': '<ul class="list-disc list-inside">',
                                    '<ol>': '<ol class="list-decimal list-inside">'
                                }
                            )|raw }}
                        </div>
                    {% endblock %}

                    {% block event_link %}
                        {% if this.event.url %}
                            <div>
                                <a href="{{ this.event.url }}"
                                   target="_blank"
                                   title="{{ this.event.name }}"
                                   class="inline-flex items-center rounded border border-transparent bg-emerald-700 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-emerald-800 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2">
                                    {{ 'event.read_more'|trans }}
                                    &nbsp;
                                    {{ svg(
                                        file = 'icons/mini/arrow-top-right-on-square.svg',
                                        width = 12,
                                        height = 12
                                    ) }}
                                </a>
                            </div>
                        {% endif %}
                    {% endblock %}
                </div>
                <div class="whitespace-nowrap text-right text-sm text-gray-500">
                    {% block event_date %}
                        <time datetime="{{ this.event.startAt|date('Y-m-d H:i:s') }}">
                            {{ this.event.startAt|date('M j Y') }}
                        </time>
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/components/skill.html.twig
{% block skill %}
    <span title="{{ this.skill.description }}"
          class="cursor-help inline-flex items-center rounded-full hover:bg-emerald-600 hover:text-white bg-gray-100 mb-2.5 mr-0.5 px-2.5 py-0.5">
        {{ svg(
            file = 'icons/outline/hashtag.svg',
            width = 12,
            height = 12
        ) }}{{ this.skill }}
    </span>
{% endblock %}

templates/components/testimonial.html.twig
{% block testimonial %}
    {% set imageWidth = 64 %}

    <div class="pt-8 sm:inline-block sm:w-full sm:px-4">
        <figure class="rounded-2xl bg-gray-50 p-8 text-sm/6">
            <blockquote class="text-gray-900 space-y-3">
                {{ testimonial.content|markdown }}
            </blockquote>
            <figcaption class="mt-6 flex items-center gap-x-4">
                {{ testimonial.avatar|image(
                    width = imageWidth,
                    height = 'auto',
                    alt = testimonial.name,
                ) }}
                <div>
                    <a href="{{ testimonial.url }}" rel="noreferrer nofollow" class="font-semibold text-gray-900" target="_blank">{{ testimonial.name }}</a>
                    <div class="text-gray-600">{{ testimonial.relation }}</div>
                    <div class="text-gray-600">{{ testimonial.date|date('M d Y') }}</div>
                </div>
            </figcaption>
        </figure>
    </div>
{% endblock %}